# Generated by Django 4.0.5 on 2022-06-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASInformation',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('range_start', models.TextField()),
                ('range_end', models.TextField(default='0.0.0.0')),
                ('as_number', models.TextField(blank=0)),
                ('country_code', models.CharField(blank=True, default=None, max_length=2)),
                ('as_description', models.TextField()),
            ],
        ),
    ]
