# Generated by Django 4.0.5 on 2022-06-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asAPI', '0002_alter_asinformation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinformation',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
